apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "qwen-coder"
  namespace: kserve-test
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  predictor:
    tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
    runtimeClassName: nvidia
    volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 2Gi
    model:
      modelFormat:
        name: huggingface
      args:
        - --model_name=qwen-coder
        - --served-model-name=qwen-coder
        - --max-model-len=65536
      volumeMounts:
        - name: dshm
          mountPath: /dev/shm
      storageUri: "pvc://qwen-coder-pvc/qwen-coder/Qwen2.5-Coder-3B-Instruct"
      resources:
        limits:
          cpu: "4"
          memory: 12Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "2"
          memory: 10Gi
          nvidia.com/gpu: "1"