apiVersion: v1
kind: PersistentVolume
metadata:
  name: qwen-coder-pv
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /var/mnt/model-store/qwen-coder
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: model-store
              operator: In
              values:
                - "true"