# Values for Argo CD Application
global:
  domain: argocd.idkthisisademo.lol

configs:
  params:
    server.insecure: true
  repositories:
    kubernetes-lab-repo:
      url: https://github.com/mimartin12/kubernetes-lab
      name: kubernetes-lab
      type: git
server:
  ingress:
    enabled: true
    ingressClassName: cilium
    annotations:
      io.cilium/lb-ipam-ips: "192.168.1.240"
      cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
    tls: true
    hosts:
      - argocd.idkthisisademo.lol
  service:
    type: ClusterIP