apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "mistral"
  namespace: kserve-test
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  predictor:
    tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
    runtimeClassName: nvidia
    volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 2Gi
    model:
      modelFormat:
        name: huggingface
      args:
        - --model_name=mistral
        - --served-model-name=mistral
        - --max-model-len=4096
        - --quantization=fp8
      volumeMounts:
        - name: dshm
          mountPath: /dev/shm
      storageUri: "pvc://model-store-pvc/Mistral-7B-Instruct-v0.1"
      resources:
        limits:
          cpu: "4"
          memory: 12Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "2"
          memory: 8Gi
          nvidia.com/gpu: "1"