apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "qwen-llm"
  namespace: kserve-test
spec:
  predictor:
    tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
    runtimeClassName: nvidia
    model:
      modelFormat:
        name: huggingface
      args:
        - --model_name=qwen
        - --served-model-name=qwen
        - --max-model-len=4096
      storageUri: "pvc://model-store-pvc/Qwen3-8B"
      resources:
        limits:
          cpu: "2"
          memory: 8Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "1"
          memory: 6Gi
          nvidia.com/gpu: "1"