apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-driver-nfs
  namespace: argocd
  labels:
    name: csi-driver-nfs
    stage: storage
spec:
  project: default
  sources:
    - repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
      targetRevision: 4.13.1
      chart: csi-driver-nfs
      helm:
        valueFiles:
          - $values/argocd/applications/values/csi-driver-nfs.yaml
        ignoreMissingValueFiles: true
    - repoURL: https://github.com/mimartin12/kubernetes-lab
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/mimartin12/kubernetes-lab
      targetRevision: HEAD
      path: argocd/applications/manifests/csi-driver
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: "5s"
        factor: 2
        maxDuration: "1m"
