apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dcgm-exporter
  namespace: argocd
  labels:
    name: dcgm-exporter
    stage: monitoring
spec:
  project: default
  sources:
    - repoURL: https://nvidia.github.io/dcgm-exporter/helm-charts
      targetRevision: 4.8.1
      chart: dcgm-exporter
      helm:
        valueFiles:
          - $values/argocd/applications/values/dcgm-exporter.yaml
        ignoreMissingValueFiles: true
    - repoURL: https://github.com/mimartin12/kubernetes-lab
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: dcgm-exporter
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
