apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  labels:
    name: external-secrets
    stage: secrets
spec:
  project: default
  sources:
    - repoURL: https://charts.external-secrets.io
      targetRevision: 2.1.0
      chart: external-secrets
      helm:
        valueFiles:
          - $values/argocd/applications/values/external-secrets.yaml
        ignoreMissingValueFiles: true
    - repoURL: https://github.com/mimartin12/kubernetes-lab
      targetRevision: HEAD
      ref: values
    # Additional configuration, such as SecretStores
    - repoURL: https://github.com/mimartin12/kubernetes-lab
      targetRevision: HEAD
      path: argocd/applications/manifests/external-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: "5s"
        factor: 2
        maxDuration: "1m"
