apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-alloy-operator
  namespace: argocd
  labels:
    name: grafana-alloy-operator
    stage: monitoring
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      targetRevision: 0.5.0
      chart: alloy-operator
      helm:
        valueFiles:
          - $values/argocd/applications/values/grafana-alloy-operator.yaml
        ignoreMissingValueFiles: true
    - repoURL: https://github.com/mimartin12/kuberentes-lab
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/mimartin12/kuberentes-lab
      targetRevision: HEAD
      path: argocd/applications/manifests/grafana-alloy
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana-alloy-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: "5s"
        factor: 2
        maxDuration: "1m"
