apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
  labels:
    name: keda
    stage: scaling
spec:
  project: default
  sources:
    - repoURL: https://kedacore.github.io/charts
      targetRevision: 2.20.2
      chart: keda
      helm:
        valueFiles:
          - $values/argocd/applications/values/keda.yaml
        ignoreMissingValueFiles: true
    - repoURL: https://kedacore.github.io/charts
      targetRevision: 0.15.0
      chart: keda-add-ons-http
      helm:
        valueFiles:
          - $values/argocd/applications/values/keda-add-ons-http.yaml
        ignoreMissingValueFiles: true
    - repoURL: https://github.com/mimartin12/kubernetes-lab
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/mimartin12/kubernetes-lab
      targetRevision: HEAD
      path: argocd/applications/manifests/keda
  destination:
    server: https://kubernetes.default.svc
    namespace: keda
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: "5s"
        factor: 2
        maxDuration: "1m"
