apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kserve
  namespace: argocd
  labels:
    name: kserve
    stage: ai
spec:
  project: default
  sources:
    - repoURL: oci://ghcr.io/kserve/charts/kserve
      targetRevision: v0.16.0
      chart: kserve
      helm:
        valueFiles:
          - $values/argocd/applications/values/kserve.yaml
        ignoreMissingValueFiles: true
    - repoURL: https://github.com/mimartin12/kubernetes-lab
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/mimartin12/kubernetes-lab
      targetRevision: HEAD
      path: argocd/applications/manifests/kserve-models
  destination:
    server: https://kubernetes.default.svc
    namespace: kserve
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: "5s"
        factor: 2
        maxDuration: "1m"
